[package]
name = "Arena"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
tokio = { verison = "1", features = ["full"] }
mio = "0.8"
log = "0.4.0"
env_logger = "0.9.0"
